version: '3'
networks:
  development:
  test:
services:
  db:
    image: postgres:13
    environment: 
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
    networks:
      - development
      - test
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    tty: true
    stdin_open: true
    networks:
      - development
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      ELASTIC_SEARCH_URL: 'es-container:9200'
      DATABASE_HOST: "db"
      DATABASE_USERNAME: "admin"
      DATABASE_PASSWORD: "password"
      DATABASE_PORT: 5432
      EDITOR: "vim"
    volumes:
      - .:/raccoon:delegated
      - bundle:/usr/local/bundle
      - cache:/raccoon/tmp/cache
  web_test:
    image: raccoon_web
    container_name: holder-test
    entrypoint: test-entrypoint.sh
    command: ["rails", "-v"]
    stdin_open: true
    volumes:
      - .:/raccoon:delegated
      - bundle:/usr/local/bundle
      - cache:/raccoon/tmp/cache
    tty: true
    ports:
      - "9000:3000"
    networks:
      - test
    depends_on:
      - db
    environment:
      ELASTIC_SEARCH_URL: 'es-container:9200'
      DATABASE_HOST: "db"
      DATABASE_USERNAME: "admin"
      DATABASE_PASSWORD: "password"
      DATABASE_PORT: 5432
      RAILS_ENV: test
      SWAGGER_DRY_RUN: 0
volumes:
  postgres:
  cache:
  bundle: 
